<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
*/
// User routes...
Route::apiResource('user', 'Api\UserController');
// UserBasicInfo routes...
Route::apiResource('user-basic-info', 'Api\UserBasicInfoController');
// UserResidentialInfo routes...
Route::apiResource('user-residential-info', 'Api\UserResidentialInfoController');
// SocialSite routes...
Route::apiResource('social-site', 'Api\SocialSiteController');
// UserSocialAccount routes...
Route::apiResource('user-social-account', 'Api\UserSocialAccountController');
// Module routes...
Route::apiResource('module', 'Api\ModuleController');
// Role routes...
Route::apiResource('role', 'Api\RoleController');
// Permission routes...
Route::apiResource('permission', 'Api\PermissionController');
