<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/


// Company routes...
Route::resource('company', 'CompanyController');
// Admin routes...
Route::resource('admin', 'AdminController');
// Client routes
Route::prefix('client')->name('client-')->group(function () {
    // request routes...
    Route::resource('request', 'ClientRequestController')->except(['create']);
    // list routes...
    Route::resource('approved', 'ClientApprovedController')->except(['create']);
});
// User profile routes
Route::prefix('profile')->name('profile-')->group(function () {
    // UserBasicInfo routes...
    Route::resource('basic-info', 'Profile\BasicInfoController')->only(['index', 'update']);
    // UserAccountInfo routes...
    Route::resource('account-info', 'Profile\AccountInfoController');
    // UserResidentialInfo routes...
    Route::resource('residential-info', 'Profile\ResidentialInfoController')->only(['index', 'update']);
    // UserSocialAccount routes...
    Route::resource('social-account', 'Profile\SocialAccountController')->except(['show']);
    // ChangePassword routes...
    Route::resource('change-password', 'Profile\ChangePasswordController');
});
// UserBasicInfo routes...
Route::resource('user-basic-info', 'UserBasicInfoController');
// UserResidentialInfo routes...
Route::resource('user-residential-info', 'UserResidentialInfoController');
// SocialSite routes...
Route::resource('social-site', 'SocialSiteController');
// UserSocialAccount routes...
Route::resource('user-social-account', 'UserSocialAccountController');
// Role routes...
//Route::resource('role', 'RoleController');
// Permission routes...
//Route::resource('permission', 'PermissionController');
